services:
  aptify:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - apt-data:/data
    environment:
      - DATA_DIR=/data
      - ADDR=:8080
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      # Optional: Set a consistent JWT secret to prevent session invalidation on server restart
      # Generate the key using openssl rand -hex 32 or go run genkey.go
      - JWT_SECRET=YOUR_GENERATED_STRING_HERE
      - KEY_NAME="APT Repository"
      - KEY_EMAIL="abc@example.com"
      # To use SQlite, comment the lines below and the db service:
      - DB_TYPE=mysql
      - DB_DSN=aptify:aptifypass@tcp(db:3306)/aptify?parseTime=true
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=aptify
      - MYSQL_USER=aptify
      - MYSQL_PASSWORD=aptifypass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  apt-data:
  mysql-data:
